### ISSUE TITLE
Wamp Protocol

### ISSUE THREAD

**Issue by joelwurtz** [amphp/websocket-server#5]
I was wondering if the Wamp Protocol could be a part of this lib or if you would prefer to have it as an external library ?

**Comment by bwoebi** [comment]
I'd prefer to have it as an external library, this lib is really about RFC 6455. WAMP is just an arbitrary, albeit widely supported protocol on top of this.

**Comment by kelunik** [comment]
I'm going to close this, as I also think a separate package will be better.
